#+TITLE: Gnome Sort (Stupid Sort)
#+AUTHOR: Andrej Karafiloski
#+OPTIONS: ^:nil

Gnome Sort, исто познат како и *Stupid Sort* е варијација на *insertion sort* кој не користи вгнездени циклуси

* Како работи алгоритамот
Алгоритамот користи еден циклус кои врти се додека индексот i(почетна вредност е 1 за 0-индекс низа) е помал од бројот на елементи во низата. При едно вртење на циклусот проверува дали моменталниот елемент е помал од претходниот елемент. Ако ова важи се менуваат местата на двата елемента и се менува индексот за -1. Ако индексот i е 0 или сегашниот елемент е поголем или еднаков на претходниот i се менува за +1.

>Gnome Sort is based on the technique used by the standard Dutch Garden Gnome.
>Here is how a garden gnome sorts a line of flower pots.
>Basically, he looks at the flower pot next to him and the previous one; if they are in the right order he steps one pot forward, otherwise, he swaps them and steps one pot backward.
>Boundary conditions: if there is no previous pot, he steps forwards; if there is no pot next to him, he is done.
>> "Gnome Sort - The Simplest Sort Algorithm". Dickgrune.com

* Временска комплексност на алгоритамот
Очигледно е дека најлошиот случај за Gnome sort е кога целата низа е подредена во опаѓачки редослед $a_0 > a_1 >...> a_{n-1}$ во овој случај секој елемент ќе биде преместен до позиција 0 пред да оди на следниот елемент, така временската комплексност ќе е еднаква на збирот на броеви од 0 до n-1

$\mathcal{O}(\sum_{i=0}^{n-1}i) = \mathcal{O}(\frac{n(n-1)}{2}) = \mathcal{O}(\frac{n^2-n}{2})$

константи и помали променливи не се сметаат $n^{2}$ многу побрзо ќе расте отколку $-n$ па крајната комплексност е $\mathcal{O}(n^2)$

* Време потребно да се сортира низа со n елементи (in nanoseconds):

Спецификации на компјутер на кој се правени овие benchmarks:
+ OS: Fedora Linux 44 (KDE Plasma Desktop Edition) x86_64
+ CPU: Intel(R) Core(TM) i5-9400 (6) @ 4.10 GHz
+ Memory: 15.5GiB

| Size of n | time needed |
|-----------+-------------|
|       100 | 21598ns     |
|      1000 | 1873584ns   |
|     10000 | 207217\mu{}s    |
|    100000 | 17967915\mu{}s  |
|   1000000 | >1.5h       |
|  10000000 | >1.5h       |
|-----------+-------------|
* Како да се компајлира
Потребно е cmake со верзија поголема или еднаква на 3.15 и компајлер за c++ 14 или понова верзија

командиве да се извршат внатре во папката =domasna2_gnome=

#+begin_src bash
  cmake -S . -B build
  cmake --build build
  #+end_src

потоа за да се изврши main.cpp или time_benchmarks.cpp
#+begin_src bash
  ./build/time_benchmarks.cpp
  ./build/main
  #+end_src

* Пример за Gnome Sort на низа од 5 елементи

0. чекор

    низата е:
    | 4 | 1 | 2 | 5 | 3 |

    i = 1 (0 индекс низа)

1. чекор
   
   |   | i |   |   |   |
   | 4 | 1 | 2 | 5 | 3 |

   го споредува 1 со 4, и поради тоа што 1 < 4, им се заменуваат местата и i се враќа за едно место наназад (i-1)

2. чекор
   
   | i |   |   |   |   |
   | 1 | 4 | 2 | 5 | 3 |

   Поради тоа што i = 0, нема број со индекс помал од 0 па i се поместува за едно место понапред (i+1)

3. чекор
   
   |   | i |   |   |   |
   | 1 | 4 | 2 | 5 | 3 |   

   4 > 1, па не си ги заменуваат местата и i+1

4. чекор
   
   |   |   | i |   |   |
   | 1 | 4 | 2 | 5 | 3 |   

   2 < 4, па се заменувата нивните места и i-1  

5. чекор
   
   |   | i |   |   |   |
   | 1 | 2 | 4 | 5 | 3 |   

   2 > 1, па не си ги заменуваат местата и i+1

6. чекор
   
   |   |   | i |   |   |
   | 1 | 2 | 4 | 5 | 3 |

   4 > 2, па не си ги заменуваат местата и i+1

7. чекор
   
   |   |   |   | i |   |
   | 1 | 2 | 4 | 5 | 3 |

   5 > 4, па не си ги заменуваат местата и i+1

8. чекор
   
   |   |   |   |   | i |
   | 1 | 2 | 4 | 5 | 3 |

   3 < 5, па се заменувата нивните места и i-1  

9. чекор
   
   |   |   |   | i |   |
   | 1 | 2 | 4 | 3 | 5 |

   3 < 4, па се заменувата нивните места и i-1

10. чекор
   
   |   |   | i |   |   |
   | 1 | 2 | 3 | 4 | 5 |

   3 > 2, па не си ги заменуваат местата и i+1

10. чекор
   
   |   |   |   | i |   |
   | 1 | 2 | 3 | 4 | 5 |

   4 > 3, па не си ги заменуваат местата и i+1

10. чекор
   
   |   |   |   |   | i |
   | 1 | 2 | 3 | 4 | 5 |

   5 > 4, па не си ги заменуваат местата и i+1

11. чекор
     
   |   |   |   |   |   | i |
   | 1 | 2 | 3 | 4 | 5 |   |

   условот на циклусот е (i < arr_len), во овој чекор i == arr_len (поради тоа што е 0 индекс, т.е последниот елемент има индекс arr_len-1) па условот за да продолжи циклусот не е исполнет, циклусот завршува и низата е сортирана 
